evan.ninetyfivetees.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using evan.ninetyfivetees.web.Models;
using Microsoft.EntityFrameworkCore;

namespace evan.ninetyfivetees.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ninetyfiveteesContext _context;

        public HomeController(ninetyfiveteesContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Shirts> shirts = await _context.Shirts.Include(s => s.Color).Include(s => s.Design).Take(5).ToListAsync();
            return View(shirts);
        }

        public IActionResult About()
        {
            ViewData["activePage"] = "about";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

evan.ninetyfivetees.web/Controllers/aboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace evan.ninetyfivetees.web.Controllers
{
    public class aboutController : Controller
    {
        public IActionResult Index()
        {
            ViewData["activePage"] = "about";

            return View();
        }
    }
}

evan.ninetyfivetees.web/Controllers/merchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using evan.ninetyfivetees.web.Models;

namespace evan.ninetyfivetees.web.Controllers
{
    public class merchController : Controller
    {
        private readonly ninetyfiveteesContext _context;

        public merchController(ninetyfiveteesContext context)
        {
            _context = context;
        }

        // GET: merch
        public async Task<IActionResult> Index(int minPrice = 0, int maxPrice = 0, int size = 0, int gender = 0, int design = 0, int season = 0)
        {
            var ninetyfiveteesContext = _context.Shirts.Include(s => s.Color).Include(s => s.Design).Include(s => s.Size).Include(s => s.Gender).Include(s => s.Season);
            IQueryable<Shirts> data = ninetyfiveteesContext;

            if (design != 0)
            {
                data = data.Where(c => c.DesignId == design);
                ViewData["designId"] = design;
            }

            if (size != 0)
            {
                data = data.Where(c => c.SizeId == size);
                ViewData["sizeId"] = size;
            }

            if (gender != 0)
            {
                data = data.Where(c => c.GenderId == gender);
                ViewData["genderId"] = gender;
            }

            if (season != 0)
            {
                data = data.Where(c => c.SeasonId == season);
                ViewData["SeasonId"] = season;
            }

            if (maxPrice != 0)
            {
                data = data.Where(c => c.Price >= minPrice && c.Price <= maxPrice);
                ViewData["minPrice"] = minPrice;
                ViewData["maxPrice"] = maxPrice;
            }

            return View(await data.ToListAsync());
        }

        // GET: merch/Details/5
        [ActionName("view")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirts = await _context.Shirts
                .Include(s => s.Color)
                .Include(s => s.Design)
                .Include(s => s.Size)
                .Include(s => s.Gender)
                .Include(s => s.Season)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shirts == null)
            {
                return NotFound();
            }

            return View("Details", shirts);
        }

        // GET: merch/Create
        public IActionResult Create()
        {
            ViewData["ColorId"] = new SelectList(_context.Color, "Id", "Name");
            ViewData["DesignId"] = new SelectList(_context.Designs, "Id", "Name");
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Name");
            ViewData["SeasonId"] = new SelectList(_context.YearSeasons, "Id", "Name");
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "Description");
            return View();
        }

        // POST: merch/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Shirts shirts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shirts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ColorId"] = new SelectList(_context.Color, "Id", "Id", shirts.ColorId);
            ViewData["DesignId"] = new SelectList(_context.Designs, "Id", "Id", shirts.DesignId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Id", shirts.SizeId);
            return View(shirts);
        }

        // GET: merch/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirts = await _context.Shirts.SingleOrDefaultAsync(m => m.Id == id);
            if (shirts == null)
            {
                return NotFound();
            }
            ViewData["ColorId"] = new SelectList(_context.Color, "Id", "Id", shirts.ColorId);
            ViewData["DesignId"] = new SelectList(_context.Designs, "Id", "Id", shirts.DesignId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Id", shirts.SizeId);
            return View(shirts);
        }

        // POST: merch/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DesignId,SizeId,ColorId,Description,Title,Price")] Shirts shirts)
        {
            if (id != shirts.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shirts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShirtsExists(shirts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ColorId"] = new SelectList(_context.Color, "Id", "Id", shirts.ColorId);
            ViewData["DesignId"] = new SelectList(_context.Designs, "Id", "Id", shirts.DesignId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Id", shirts.SizeId);
            return View(shirts);
        }

        // GET: merch/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirts = await _context.Shirts
                .Include(s => s.Color)
                .Include(s => s.Design)
                .Include(s => s.Size)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shirts == null)
            {
                return NotFound();
            }

            return View(shirts);
        }

        // POST: merch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shirts = await _context.Shirts.SingleOrDefaultAsync(m => m.Id == id);
            _context.Shirts.Remove(shirts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShirtsExists(int id)
        {
            return _context.Shirts.Any(e => e.Id == id);
        }
    }
}

evan.ninetyfivetees.web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

evan.ninetyfivetees.web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

evan.ninetyfivetees.web/Views/Home/Index.cshtml
@model IEnumerable<evan.ninetyfivetees.web.Models.Shirts>
@{
    ViewData["Title"] = "Home";
    ViewData["activePage"] = "home";
}


<div class="slider">
    @foreach (Shirts item in Model)
    {
        <div class="slide-item" style="background-image:url(@item.Image)">
            <div class="overlay">
                <div class="content">
                    <span class="title">@item.Title</span>
                    <p>@item.Description</p>
                    <a asp-controller="merch" asp-action="view" asp-route-id="@item.Id" class="button light lined">View Deal</a>
                </div>
            </div>
        </div>
    }
    <div class="navigator"></div>
</div>
<script src="~/js/slider.js" asp-append-version="true"></script>

<div class="homepage-about">
    <div class="entry-content">
        <h1>Welcome to 95 Tees</h1>
        <p class="about-body">
            Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
            Tincidunt integer eu augue augue nunc elit dolor, aliquam sit amet justo nunc tempor, metus vel.
            Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
        </p>
        <div class="actions">
            <a href="#" class="button dark lined">Find out more</a>
            <a asp-controller="merch" asp-action="" class="button dark">Shop Now</a>
        </div>
    </div>
</div>

<div class="shop-categories">
    <a asp-controller="merch" asp-action="" asp-route-gender="1" class="male col">
        <div class="overlay">
            <span>Shop Male Shirts</span>
        </div>
    </a>

    <a asp-controller="merch" asp-action="" asp-route-gender="2" class="female col">
        <div class="overlay">
            <span>Shop Female Shirts</span>
        </div>
    </a>
</div>